spring.application.name=chat-bot-open-ai

spring.ai.openai.api-key={{SPRING.AI.OPENAI.API-KEY}}

# logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan}:\t%msg%n
# logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.console=%clr(%d{mm:ss.SSS}){green} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

logging.level.org.springframework.ai.chat.client.advisor=DEBUG


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:latest